{{- range $gi, $group := .Values.groups }}
{{- if $group.authorization }}
{{- range $ai, $auth := $group.authorization }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $group.name }}-binding
  namespace: {{ $auth.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $group.name }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $group.name }}
{{- end }}
{{- end }}
{{- end }}